### ISSUE TITLE
support stdin/stdout ?

### ISSUE THREAD

**Issue by devZer0** [theraser/blocksync#19]
would it be possible to have support for stdin/stdout with blocksync ?

using "-" as filename does not seem to work

this would be useful, because for example with borg backup you could avoid fuse mounting the borg archive to access the archive and use borg extract directly, for example

borg extract --stdout /mnt/repo1::sda_07_10_2022  |  blocksync.py - localhost /dev/sdc

**Comment by ct16k** [comment]
Haven't tested this (it has been years since I last used this script and I don't have a python2 env anymore), but you may already be able to do that, by using `/dev/stdin` as your source. One limitation of this approach is you won't be able to use multiple workers, as `stdin` is not seek-able.

**Comment by devZer0** [comment]
it does not work with /dev/stdin, but no problem, blocksync from shodanshock at https://github.com/shodanshok/blocksync  did implement it in the meantime , so i'm happily using that now :)))

the error i'm getting with

borg extract --stdout /mnt/repo2::sda_07_10_2022 >/dev/null  | /root/blocksync.py /dev/stdin - localhost /dev/sdc

is

```
# borg extract --stdout /mnt/repo2::sda_07_10_2022 >/dev/null  | /root/blocksync.py /dev/stdin - localhost /dev/sdc

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!                                          !!!
!!! DESTINATION WILL BE PERMANENTLY CHANGED! !!!
!!!         PRESS CTRL-C NOW TO EXIT         !!!
!!!                                          !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Starting worker #0 (pid: 6481)
[worker 0] Block size is 1.0 MB
[worker 0] Local fadvise: None
[worker 0] Error accessing source device! [Errno 29] Illegal seek
Worker #0 exited with 256
Worker #0 caused ABORT

**Comment by ct16k** [comment]
Glad you found a solution that works for you!
