### ISSUE TITLE
Can I use blocksync for sync two local devices?

### ISSUE THREAD

**Issue by geaplanet** [theraser/blocksync#2]
I cloned several 32Gb pendrives with a linux system installed using dd. Later I did shrink a partition and I did some little more changes (in the "Master"). With blocksync could I transfer only the blocks changed for avoiding the superslow full re-cloning with dd?

**Comment by ct16k** [comment]
That should be precisely the case blocksync.py was made for. To copy to a local destination, just specify _localhost_ as the remote host.
