### ISSUE TITLE
Allow sync not only for devices but also for files

### ISSUE THREAD

**Issue by klemens-u** [theraser/blocksync#3]
That would be really helpful.

In the meantime I use kpartk to loop an image file as a block device.
Is this dangerous?

Thanks!

**Comment by ct16k** [comment]
It should work OK for files as well. Actually I've only used it for (very large) files. Are you seeing a different behavior than intended?

**Comment by theraser** [comment]
I can remember some problems with this, too. But after testing it now it just works fine. I will close this issue for now, please let me know when there this problem occurs again.
