### ISSUE TITLE
Is it safe to use --createdest on subsequent syncs?

### ISSUE THREAD

**Issue by klemens-u** [theraser/blocksync#6]
It's not clear from help if --createdest option is safe to use when the target files already exists.
Is --createdest simply ignored when the target already exists?

`blocksync.py --help`
`    -T, --createdest      create destination file using truncate(2)`

**Comment by ct16k** [comment]
It's always called, but should be safe to use, as `truncate()` modifies the file only if it's given a different file size than the current one (it either truncates it to a lower size or pads it with zeros if larger).

**Comment by klemens-u** [comment]
OK, thanks. A test by me confirms that. See my pull request for help update

**Comment by ct16k** [comment]
Merged #7
